Set-StrictMode -Version 3.0

. $PSScriptRoot\..\private\Get-CommonArguments.ps1
. $PSScriptRoot\..\private\Get-TaggedOutputDir.ps1

# Valid export formats. This is exported from the module so that it can be accessed from ArgumentCompleter:
$g_NhcVcpkgValidExportFormats = @( "zip", "7zip", "tgz" )

function Export-NhcVcpkgPorts {
    <#
    .SYNOPSIS
    Exports installed vcpkg ports.

    .DESCRIPTION
    This function wraps the 'vcpkg export' command to provide additional functionality that is inconvenient or impossible to script using response files alone (e.g. versioned exports). VCPKG_* environment variables are respected unless overridden by a corresponding parameter passed to the function.

    Note: Requires vcpkg 2024-11-12 or newer for '--classic' support.

    .PARAMETER Ports
    Exports only the specified ports. Note that vcpkg will be called with '--classic' to ignore a manifest file if present. Cannot be combined with All.

    .PARAMETER All
    Exports all installed ports. Cannot be combined with Ports.

    .PARAMETER Raw
    Export to a directory. The default is './export'.

    .PARAMETER Format
    Specify an export file format:
    - 7zip - Export to a .7z file.
    - Zip  - Export to a .zip file.
    - Tgz  - Export to a .tgz file.

    .PARAMETER OutputDir
    Specifies a directory for the export. Defaults to './export' for raw exports and the current working directory for file-based exports. The directory will be created if it does not exist. An error will be raised if a raw export is requested, OutputDir is the current directory, and Tag is not passed.

    .PARAMETER Tag
    Creates a subdirectory under OutputDir for the export. If a non-empty string is passed, it will be used for the directory name. Otherwise, a timestamp with format "yyyyMMdd-hhmmss" will be used as the directory name. Note that the string must be a valid file name without '/' or '\'.

    .PARAMETER Output
    Specifies the base name for a file export. If not passed, the default generated by vcpkg is 'vcpkg-export-<timestamp>'. Cannot be combined with Raw.

    .PARAMETER Quiet
    Suppresses all output from the vcpkg command, including errors.

    .PARAMETER Command
    Specifies the path to the vcpkg executable to call.

    .PARAMETER RootDir
    Specifies the <vcpkg-root> to use. If not passed, <vcpkg-root> is detected from either Command or $env:VCPKG_ROOT.

    .PARAMETER Triplet
    Specifies the target triplet (e.g., x64-windows). Auto-detected if not provided.

    .PARAMETER OverlayPorts
    Specifies one or more paths to overlay ports.

    .PARAMETER ManifestDir
    Specifies the directory containing 'vcpkg.json'. Only used if All is passed.

    .PARAMETER InstallDir
    Specifies the path to the installed ports. The path must exist, and defaults to '<vcpkg-root>/installed'.

    .EXAMPLE
    Export-NhcVcpkgPorts -All -Format zip -Tag ''

    Exports all installed ports from '<vcpkg-root>/installed' to './<yyyyMMdd-hhmmss>/vcpkg-export.zip'.

    .EXAMPLE
    Export-NhcVcpkgPorts -Ports fmt -Format zip -Output 'fmt-release'

    Export 'fmt' from '<vcpkg-root>/installed' to './fmt-release.zip'.

    .EXAMPLE
    Export-NhcVcpkgPorts -Ports boost-filesystem,fmt -Format tgz -Triplet x64-linux

    Exports only 'boost-filesystem' and 'fmt' ports from '<vcpkg-root>'/installed for the x64-linux triplet to './vcpkg-export.tgz'.

    .EXAMPLE
    Export-NhcVcpkgPorts -Ports zlib -Raw -InstallDir '/vcpkg-data/installed' -OutputDir '.' -Tag ''

    Raw export of 'zlib' from '/vcpkg-data/installed' to './<yyyyMMdd-hhmmss>/...' using the default root for version control.

    .EXAMPLE
    Export-NhcVcpkgPorts -Ports zlib -Raw -RootDir '/vcpkg-root' -OutputDir '.' -Tag ''

    Raw export of 'zlib' from '/vcpkg-root/installed' to './<yyyyMMdd-hhmmss>/...'.

    .EXAMPLE
    Export-NhcVcpkgPorts -Ports zlib -Format 7zip -RootDir '/vcpkg-root' -OutputDir '.' -Output 'zlib-current' -Tag ''

    Export 'zlib' from '/vcpkg-root/installed' to './<yyyyMMdd-hhmmss>/zlib-current.7z'.

    .EXAMPLE
    Export-NhcVcpkgPorts -Ports zlib -Format tgz -Vcpkg '/vcpkg-root/vcpkg' -RootDir '/vcpkg-root' -Tag ''

    Export 'zlib' from '/vcpkg-root/installed' to './export/<yyyyMMdd-hhmmss>/vcpkg-export.tgz'.

    .OUTPUTS
    Returns a hashtable with fields:
    - Command: the full vcpkg executable path
    - Arguments: An array of strings that can be used to invoke vcpkg using Start-Process.
    - RootDir: The vcpkg root directory.
    - BaseDir = @{ Path, Exists }: OutputDir without the Tag if OutputDir was passed, $null otherwise.
    - OutputDir = @{ Path, Exists }: The output directory including the Tag if it was passed or generated.
    - InstallDir = @{ Path, Exists }: The string passed to --x-install-root.
    - Tag: The tag if one was passed or generated, $null otherwise.

    The "Exists" fields indicate whether or not the corresponding directory existed before this function was invoked.

    .LINK
    https://learn.microsoft.com/en-us/vcpkg/commands/export
    #>

    [CmdletBinding(SupportsShouldProcess = $true)]
    param (
        [Parameter(ParameterSetName = "PortsRaw", Mandatory = $true, Position = 0)]
        [Parameter(ParameterSetName = "PortsFile", Mandatory = $true, Position = 0)]
        [string[]]$Ports,

        [Parameter(ParameterSetName = "AllRaw", Mandatory = $true)]
        [Parameter(ParameterSetName = "AllFile", Mandatory = $true)]
        [switch]$All,

        [Parameter(ParameterSetName = "PortsRaw", Mandatory = $true)]
        [Parameter(ParameterSetName = "AllRaw", Mandatory = $true)]
        [switch]$Raw,

        [Parameter(ParameterSetName = "PortsFile", Mandatory = $true)]
        [Parameter(ParameterSetName = "AllFile", Mandatory = $true)]
        [ArgumentCompleter({
                param($ign0, $ign1, $word, $ign3, $ign4)
                $g_NhcVcpkgValidExportFormats | Where-Object { $_ -like "$word*" }
            })]
        [string]$Format,

        [Parameter(ParameterSetName = "PortsFile")]
        [Parameter(ParameterSetName = "AllFile")]
        [string]$Output,

        [Parameter(ParameterSetName = "AllRaw")]
        [Parameter(ParameterSetName = "AllFile")]
        [string]$ManifestDir,

        [string]$OutputDir,

        [AllowEmptyString()]
        [string]$Tag,

        [switch]$Quiet,
        [string]$Command,
        [string]$Triplet,
        [string]$RootDir,
        [string]$InstallDir,
        [string[]]$OverlayPorts
    )

    begin {
        if (-not $PSBoundParameters.ContainsKey('ErrorAction')) {
            $ErrorActionPreference = [System.Management.Automation.ActionPreference]::Stop
        }

        # Validate Format here. ValidateSet() does not play nicely with ParameterSet:
        if ($PSBoundParameters.ContainsKey("Format")) {
            if (-not $g_NhcVcpkgValidExportFormats.Contains($Format.ToLower())) {
                Write-Error "Invalid format '$Format'"
            }
        }
    }

    process {
        # Directory arguments required by vcpkg export:
        $private:required = @( 'OutputDir', 'InstallDir' )

        # Directories potentially created by vcpkg export:
        $private:created = @( 'BaseDir', 'OutputDir' )

        # Simplify testing below:
        $Format = $Format.ToLower()

        # Generate a custom OutputDir if requested:
        $private:splat = $null
        if ($PSBoundParameters.ContainsKey("OutputDir")) {
            $splat += @{ OutputDir = $OutputDir }
        }
        elseif ($Raw) {
            $splat += @{ OutputDir = './exports' }
        }
        else {
            $splat += Get-Location
        }
        if ($PSBoundParameters.ContainsKey("Tag")) {
            $splat += @{ Tag = $Tag }
        }
        $private:tagged = Get-TaggedOutputDir @splat -AllowCwd:$false
        $splat = $null

        if ($null -eq $tagged.OutputDir) {
            Write-Error "Could not determine a valid output directory."
        }

        # If the target exists and could be an existing raw export or vcpkg root, raise an error to avoid overwriting it:
        if ($Raw) {
            $private:dir = $tagged.OutputDir.Path
            if (Test-VcpkgRoot -Path $dir) {
                Write-Error "A raw export would overwrite '$dir', which appears to be a vcpkg root directory or an existing raw export."
            }
        }
        elseif ($PSBoundParameters.ContainsKey("Output")) {
            $private:dir = Join-RelativePath -Path $tagged.OutputDir.Path -ChildPath $Output
            if (Test-VcpkgRoot -Path $dir) {
                Write-Error "An archive export would overwrite '$dir', which appears to be a vcpkg root directory or an existing raw export."
            }
        }

        # Return BaseDir, OutputDir, and Tag with $config:
        $private:config = @{}
        $config += @{ BaseDir = $tagged.BaseDir }
        $config += @{ OutputDir = $tagged.OutputDir }
        $config += @{ Tag = $tagged.Tag }

        # Build the common vcpkg arguments list:
        $PSBoundParameters.OutputDir = $tagged.OutputDir.Path
        $config += Get-CommonArguments -Parameters $PSBoundParameters -Directories $required

        $private:exe = $config.Command
        $private:verb = 'export'

        $private:params = @()
        $params += $verb
        $params += $config.Arguments

        # Export-specific vcpkg arguments:
        if ($Raw) {
            $params += "--raw"
        }
        elseif ($PSBoundParameters.ContainsKey("Format")) {
            $params += "--$Format"
        }

        # Add --output:
        if ($Raw) {
            # Disable the extra output for raw exports:
            $params += "--output=`"`""
        }
        elseif ($PSBoundParameters.ContainsKey("Output")) {
            $params += "--output=`"$Output`""
        }
        else {
            # Make the default vcpkg dated output name:
            $Output = "vcpkg-export-{0}" -f (Get-Date -Format "yyyyMMdd-HHmmss")
            $params += "--output=`"$Output`""
        }

        $private:target = $config.OutputDir.Path
        if (-not $Raw) {
            $target = Join-RelativePath -Path $target -ChildPath ("{0}.{1}" -f $Output, $Format)
        }
        Write-Verbose "Exporting to '$target'"

        if ($PSCmdlet.ShouldProcess($target, 'vcpkg export')) {
            Write-Verbose "Executing '$exe $params'"
        }
        else {
            Write-Host "Whatif: Would execute '$exe $params'"
            $params += "--dry-run"
        }

        if ($Quiet) {
            Start-Process -FilePath $exe -ArgumentList $params -NoNewWindow -Wait -WhatIf:$false 2>&1 | Out-Null
        }
        else {
            Start-Process -FilePath $exe -ArgumentList $params -NoNewWindow -Wait -WhatIf:$false
        }


        # Try to clean up after --dry-run:
        if ($WhatIfPreference) {
            # Try to clean up created output subdirectories:
            $private:todo = $created
            $private:ignore = $config.RootDir
            $todo | ForEach-Object {
                if (-not $config.ContainsKey($_)) {
                    Write-Warning "Missing expected key '$_' in `$config; ignoring"
                }
                else {
                    $private:dir = $config[$_]
                    if ($null -ne $dir) {
                        $private:clean = $dir.Path
                        if (-not $dir.Exists) {
                            # Only clean up if the path was created:
                            if (Test-Path -Path $clean -PathType Container) {
                                # Just in case:
                                if ($clean -ne $ignore) {
                                    Write-Verbose "Cleaning up output directory '$clean' for dry run"
                                    Remove-Item -Path $clean -Recurse -Force -WhatIf:$false
                                }
                            }
                        }
                        else {
                            Write-Verbose "Not removing existing directory '$clean'"
                        }
                    }
                }
            }
        }

        return $config
    }
}