schema: spec-driven

context: |
  Refer to the project root AGENTS.md if not already part of the context.

rules:
  proposal:
    - Formulate proposals around a TDD red/green/refactor process
    - Require implementing new tests when adding code
    - Require updating existing tests when changing code
    - Suggest implementing new tests when changing code that is untested
    - Keep proposals under 2000 words
  specs:
    - Formulate specs around a TDD red/green/refactor process
    - Be explicit about HOW a requirement must be met not just WHAT  must be met
  design:
    - Formulate designs around a test-driven red/green/refactor process
  tasks:
    - Break tasks into chunks of up to 2 hours of effort
    - Formulate tasks involving testing/validation around a TDD red/green/refactor process
    - Ensure all new code is validated by tasks that create new Unit tests
    - Ensure all changed code is validated by tasks that update relevant existing Unit and/or Integration tests